UPDATE tblDevice SET Description  = 'CMH - Micro Market Comm' WHERE DeviceID = 'CMH-MOX-BPV1H03'
UPDATE tblDevice SET Description  = 'LAS - Flight 8' WHERE DeviceID = 'CMH-MOX-DHP2DD3'
UPDATE tblDevice SET Description  = 'PBI - Crew Lounge' WHERE DeviceID = 'CMH-MOX-BGP2DD3'
UPDATE tblDevice SET Description  = 'CMH - Video Wall' WHERE DeviceID = 'CMH-MOX-BKWHQd2'
UPDATE tblDevice SET Description  = 'LAS - Flight 7' WHERE DeviceID = 'CMH-MOX-CGP2DD3'
UPDATE tblDevice SET Description  = 'CMH - Hanger N' WHERE DeviceID = 'CMH-MOX-BPS5H03'
UPDATE tblDevice SET Description  = 'CMH - 3 SW' WHERE DeviceID = 'CMH-MOX-BPW4H03'
UPDATE tblDevice SET Description  = 'CMH - 4 Marketing Area' WHERE DeviceID = 'CMH-MOX-BPS6H03'
UPDATE tblDevice SET Description  = 'CMH - Café SE' WHERE DeviceID = 'CMH-MOX-BPW3H03'
UPDATE tblDevice SET Description  = 'CMH - Café N' WHERE DeviceID = 'CMH-MOX-BPSXG03'
UPDATE tblDevice SET Description  = 'CMH - 4 Benefits Area' WHERE DeviceID = 'CMH-MOX-BPW1H03'
UPDATE tblDevice SET Description  = 'TEB - Crew Lounge' WHERE DeviceID = 'CMH-MOX-BPVYG03'
UPDATE tblDevice SET Description  = 'CMH - Cage SW' WHERE DeviceID = 'CMH-MOX-BPSZG03'
UPDATE tblDevice SET Description  = 'CMH - Micro Market Crew' WHERE DeviceID = 'CMH-MOX-BPVXG03'
UPDATE tblDevice SET Description  = 'CMH - 4 SW' WHERE DeviceID = 'CMH-MOX-BPT0H03'
UPDATE tblDevice SET Description  = 'CMH - 3 NW' WHERE DeviceID = 'CMH-MOX-BPV6H03'
UPDATE tblDevice SET Description  = 'CMH - Café Wall' WHERE DeviceID = 'CMH-MOX-BPT2H03'
UPDATE tblDevice SET Description  = 'CMH - Security Desk' WHERE DeviceID = 'CMH-MOX-BPV3H03'
UPDATE tblDevice SET Description  = 'CMH - Café S' WHERE DeviceID = 'CMH-MOX-BPT5H03'
UPDATE tblDevice SET Description  = 'CMH - 2 NE' WHERE DeviceID = 'CMH-MOX-BPV2H03'
UPDATE tblDevice SET Description  = 'CMH - 2 SE' WHERE DeviceID = 'CMH-MOX-BPT6H03'
UPDATE tblDevice SET Description  = 'LAS - Flight 5' WHERE DeviceID = 'CMH-MOX-BFP2DD3'
UPDATE tblDevice SET Description  = 'CMH - NetJets Store' WHERE DeviceID = 'CMH-MOX-FXQY903'
UPDATE tblDevice SET Description  = 'CMH - 2 NW' WHERE DeviceID = 'CMH-MOX-DGP2DD3'
UPDATE tblDevice SET Description  = 'CMH - 4 NE' WHERE DeviceID = 'CMH-MOX-BPTYG03'
UPDATE tblDevice SET Description  = 'VNY - Crew Lounge' WHERE DeviceID = 'CMH-MOX-6VCFFF3'
UPDATE tblDevice SET Description  = 'LAS - Flight 6' WHERE DeviceID = 'CMH-MOX-9DP2DD3'
UPDATE tblDevice SET Description  = 'LAS - Flight 3' WHERE DeviceID = 'RMT-LAS-HGP2DD3'
UPDATE tblDevice SET Description  = 'CMH - Hangar Easy Wall' WHERE DeviceID = 'CMH-MOX-6VD8FF3'
UPDATE tblDevice SET Description  = 'CMH - B1.119' WHERE DeviceID = 'CMH-MOX-3CP2DD3'
UPDATE tblDevice SET Description  = 'LAS - Flight 4' WHERE DeviceID = 'CMH-MOX-JFP2DD3'
UPDATE tblDevice SET Description  = 'LAS- Flight 9' WHERE DeviceID = 'CMH-XXX-BCP2DD3'
UPDATE tblDevice SET Description  = 'CMH - Flight Center 2' WHERE DeviceID = 'CMH-MOX-6VF8FF3'
UPDATE tblDevice SET Description  = 'LAS - Flight 2' WHERE DeviceID = 'CMH-MOX-6CP2DD3'
UPDATE tblDevice SET Description  = 'LUK - Finance' WHERE DeviceID = 'LUK-MOX-1XGF8M2'
UPDATE tblDevice SET Description  = 'VNY - Owner Lobby' WHERE DeviceID = 'CMH-MOX-6VJ6FF3'
UPDATE tblDevice SET Description  = 'LUK - Breakroom' WHERE DeviceID = 'LUK-MOX-1XH88M2'
UPDATE tblDevice SET Description  = 'CMH - Video Wall Backup' WHERE DeviceID = 'CMH-MOX-G96BQD2'
UPDATE tblDevice SET Description  = 'LAS - Flight' WHERE DeviceID = 'CMH-MOX-GCP2DD3'
